### ISSUE TITLE
Why is date_parser assuming 1 year = 360 days?

### ISSUE THREAD

**Issue by varunbalupuri** [cuemacro/findatapy#19]
In `marketdatarequest.py`, the `date_parser` method assumes 'year' is 360 days. Is there any reason why it shouldnt be 365?

```
elif date is 'year':
                date1 = date1 - timedelta(days=360)
```

https://github.com/cuemacro/findatapy/blob/fa6480c35afaaf86da5a7c72ed8d4bfdf0f355d8/findatapy/market/marketdatarequest.py#L360

**Comment by ShihHauTan** [comment]
Hi varunbalupuri, 

Sorry for the mistake.  I've just fixed it.  Thank you for noticing us!
