### ISSUE TITLE
Detailed documentation of the project

### ISSUE THREAD

**Issue by aperezlillo** [cuemacro/findatapy#37]
Hi, 

There is any detailed documentation about all the available data_sources, categories, freq, etc? I have been checking in the code but I don't anything well documented about that, please could someone help me with that? 

Thank you

**Comment by saeedamen** [comment]
Hi @aperezlillo, you can find a lot of the categories/tickers which are predefined in the https://github.com/cuemacro/findatapy/tree/master/findatapy/conf folder (in the CSV files). However, even if ticker mapping haven't been predefined, you can access them with the vendor_tickers field of MarketDataRequest.

In terms of data_sources, you can see these in the get_data_vendor method of https://github.com/cuemacro/findatapy/blob/master/findatapy/market/marketdatagenerator.py (although note some haven't been fully implemented, like boe).

**Comment by aperezlillo** [comment]
Hi @saeedamen  thank you! Would be interesting some kind of wiki in GitHub with that, but that's enough for me, thank you!
